# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='image',
            new_name='profile',
        ),
    ]
